// const usStateAbbreviations = [
//   { key: "Select State", value: "" },
//   { key: "AL", value: "AL" },
//   { key: "AK", value: "AK" },
//   { key: "AZ", value: "AZ" },
//   { key: "AR", value: "AR" },
//   { key: "CA", value: "CA" },
//   { key: "CO", value: "CO" },
//   { key: "CT", value: "CT" },
//   { key: "DE", value: "DE" },
//   { key: "FL", value: "FL" },
//   { key: "GA", value: "GA" },
//   { key: "HI", value: "HI" },
//   { key: "ID", value: "ID" },
//   { key: "IL", value: "IL" },
//   { key: "IN", value: "IN" },
//   { key: "IA", value: "IA" },
//   { key: "KS", value: "KS" },
//   { key: "KY", value: "KY" },
//   { key: "LA", value: "LA" },
//   { key: "ME", value: "ME" },
//   { key: "MD", value: "MD" },
//   { key: "MA", value: "MA" },
//   { key: "MI", value: "MI" },
//   { key: "MN", value: "MN" },
//   { key: "MS", value: "MS" },
//   { key: "MO", value: "MO" },
//   { key: "MT", value: "MT" },
//   { key: "NE", value: "NE" },
//   { key: "NV", value: "NV" },
//   { key: "NH", value: "NH" },
//   { key: "NJ", value: "NJ" },
//   { key: "NM", value: "NM" },
//   { key: "NY", value: "NY" },
//   { key: "NC", value: "NC" },
//   { key: "ND", value: "ND" },
//   { key: "OH", value: "OH" },
//   { key: "OK", value: "OK" },
//   { key: "OR", value: "OR" },
//   { key: "PA", value: "PA" },
//   { key: "RI", value: "RI" },
//   { key: "SC", value: "SC" },
//   { key: "SD", value: "SD" },
//   { key: "TN", value: "TN" },
//   { key: "TX", value: "TX" },
//   { key: "UT", value: "UT" },
//   { key: "VT", value: "VT" },
//   { key: "VA", value: "VA" },
//   { key: "WA", value: "WA" },
//   { key: "WV", value: "WV" },
//   { key: "WI", value: "WI" },
//   { key: "WY", value: "WY" },
// ];

// export default usStateAbbreviations;

const usStateAbbreviations = [
  { key: "AL", value: "AL", salesTax: 0.04 },
  { key: "AK", value: "AK", salesTax: 0 },
  { key: "AZ", value: "AZ", salesTax: 0.056 },
  { key: "AR", value: "AR", salesTax: 0.065 },
  { key: "CA", value: "CA", salesTax: 0.0725 },
  { key: "CO", value: "CO", salesTax: 0.029 },
  { key: "CT", value: "CT", salesTax: 0.0635 },
  { key: "DE", value: "DE", salesTax: 0 },
  { key: "FL", value: "FL", salesTax: 0.06 },
  { key: "GA", value: "GA", salesTax: 0.04 },
  { key: "HI", value: "HI", salesTax: 0.04 },
  { key: "ID", value: "ID", salesTax: 0.06 },
  { key: "IL", value: "IL", salesTax: 0.0625 },
  { key: "IN", value: "IN", salesTax: 0.07 },
  { key: "IA", value: "IA", salesTax: 0.06 },
  { key: "KS", value: "KS", salesTax: 0.065 },
  { key: "KY", value: "KY", salesTax: 0.06 },
  { key: "LA", value: "LA", salesTax: 0.0445 },
  { key: "ME", value: "ME", salesTax: 0.055 },
  { key: "MD", value: "MD", salesTax: 0.06 },
  { key: "MA", value: "MA", salesTax: 0.0625 },
  { key: "MI", value: "MI", salesTax: 0.06 },
  { key: "MN", value: "MN", salesTax: 0.06875 },
  { key: "MS", value: "MS", salesTax: 0.07 },
  { key: "MO", value: "MO", salesTax: 0.04225 },
  { key: "MT", value: "MT", salesTax: 0 },
  { key: "NE", value: "NE", salesTax: 0.055 },
  { key: "NV", value: "NV", salesTax: 0.0685 },
  { key: "NH", value: "NH", salesTax: 0 },
  { key: "NJ", value: "NJ", salesTax: 0.06625 },
  { key: "NM", value: "NM", salesTax: 0.05125 },
  { key: "NY", value: "NY", salesTax: 0.04 },
  { key: "NC", value: "NC", salesTax: 0.0475 },
  { key: "ND", value: "ND", salesTax: 0.05 },
  { key: "OH", value: "OH", salesTax: 0.0575 },
  { key: "OK", value: "OK", salesTax: 0.045 },
  { key: "OR", value: "OR", salesTax: 0 },
  { key: "PA", value: "PA", salesTax: 0.06 },
  { key: "RI", value: "RI", salesTax: 0.07 },
  { key: "SC", value: "SC", salesTax: 0.06 },
  { key: "SD", value: "SD", salesTax: 0.045 },
  { key: "TN", value: "TN", salesTax: 0.07 },
  { key: "TX", value: "TX", salesTax: 0.0625 },
  { key: "UT", value: "UT", salesTax: 0.0485 },
  { key: "VT", value: "VT", salesTax: 0.06 },
  { key: "VA", value: "VA", salesTax: 0.053 },
  { key: "WA", value: "WA", salesTax: 0.065 },
  { key: "WV", value: "WV", salesTax: 0.06 },
  { key: "WI", value: "WI", salesTax: 0.05 },
  { key: "WY", value: "WY", salesTax: 0.04 },
];

export default usStateAbbreviations;
